require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

$FirebaseSDKVersion = '7.8.0'


target 'ProfessorDriver' do
  config = use_native_modules!

  use_react_native!
	
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ProfessorDriverTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'ProfessorDriver-tvOS' do
  # Pods for ProfessorDriver-tvOS

  target 'ProfessorDriver-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
